import Checkout from "./Checkout";
import EditProduct from "./EditProduct";
import Home from "./Home";
import Page404 from "./Page404";
import Product from "./Product";
import ProductDtls from "./ProductDtls";
import Profile from "./Profile";
import Signin from "./Signin";
import Signup from "./Signup";
import Address from "./Address";
import EditProfile from "./EditProfile";
import Order from "./Order";
import Wishlist from "./Wishlist";
import EditAddress from "./EditAddress";
import Deals from "./Deals";
import WhatsNew from "./WhatsNew";
import SearchProduct from "./SearchProduct";
import Category from "./Category";
import ForgotPassword from "./ForgotPassword";
import ResetPassword from "./ResetPassword";

export { Checkout, EditProduct, Home, Page404, Product, Profile, Signin, Signup, Address, EditProfile, Order, Wishlist, EditAddress, ProductDtls, Deals, WhatsNew, SearchProduct, Category, ForgotPassword, ResetPassword };